# Pandas

-- Librery used for working with dataset
<br>
-- it has funvtion for analysis,cleaning,exploring & manipulating data

# Pandas Series

A Pandas Series is a fundamental, one-dimensional labeled array data structure in the Pandas library for Python. It is capable of holding data of any type (integers, strings, floats, Python objects, etc.) and is similar to a single column in a spreadsheet or a table

In [1]:
import pandas as pd
a=[1,7,2]
myvar=pd.Series(a)
print(myvar)

0    1
1    7
2    2
dtype: int64

In [2]:
print(type(myvar))

<class 'pandas.core.series.Series'>

In [3]:
print(myvar[1])

7

In [4]:
# for usermade index

a=[1,7,2]# i can take tuple also
myvar=pd.Series(a,index=['x','y','z'])
print(myvar)
print(type(myvar))

x    1
y    7
z    2
dtype: int64
<class 'pandas.core.series.Series'>

In [7]:
# print(myvar[1]) this is depricated so no longer available
print(myvar['y'])

7

In [9]:
a=(1.2,2,3,4,5,6)
myvar=pd.Series(a)
print(myvar)
print(type(myvar))

0    1.2
1    2.0
2    3.0
3    4.0
4    5.0
5    6.0
dtype: float64
<class 'pandas.core.series.Series'>

In [10]:
student_name=['ram','shyam','seeta','geeta']
marks=[60,70,80,90]
myvar=pd.Series(marks,index=student_name)
print(myvar)

ram      60
shyam    70
seeta    80
geeta    90
dtype: int64

In [2]:
import pandas as pd
student_name=['ram','shyam','seeta','geeta']
marks=[60,70,80,90]
myvar=pd.Series(marks,index=student_name,name='student_result')
print(myvar)

ram      60
shyam    70
seeta    80
geeta    90
Name: student_result, dtype: int64

In [3]:
import pandas as pd
colories={'day1':400,'day2':380,'day3':430,'day4':370}
myvar=pd.Series(colories,name='colories burn per day')
print(myvar)

day1    400
day2    380
day3    430
day4    370
Name: colories burn per day, dtype: int64

In [6]:
import pandas as pd
colories={'day1':400,'day2':380,'day3':430,'day4':370}
myvar=pd.Series(colories,name='colories burn per day',index=['day1','b'])#b is not defined
print(myvar)

day1    400.0
b         NaN
Name: colories burn per day, dtype: float64

<hr>

In [11]:
import pandas as pd
colories={'day1':400,'day2':380,'day3':430,'day4':370}
myvar=pd.Series(colories,name='colories burn per day')
print(myvar)

day1    400
day2    380
day3    430
day4    370
Name: colories burn per day, dtype: int64

In [8]:
print(myvar.size)

4

In [9]:
print(myvar.dtype)

int64

In [12]:
print(myvar.name)

colories burn per day

In [13]:
print(myvar.index)

Index(['day1', 'day2', 'day3', 'day4'], dtype='object')

In [14]:
print(myvar.values)# output in form of array not list

[400 380 430 370]

In [15]:
print(myvar.is_unique)

True

# csv

In [17]:
import pandas as pd

subs=pd.read_csv('subs.csv')
print(subs)

     Subscribers gained
0                    48
1                    57
2                    40
3                    43
4                    44
..                  ...
360                 231
361                 226
362                 155
363                 144
364                 172

[365 rows x 1 columns]

In [18]:
print(type(subs))

<class 'pandas.core.frame.DataFrame'>

In [20]:
subs=pd.read_csv('subs.csv',squeeze=True) # this is for old version 
# for new we need to use subs=pd.read_csv('subs.csv').squeeze()
# squeeze() only work in single column data
print(subs)

0       48
1       57
2       40
3       43
4       44
      ...
360    231
361    226
362    155
363    144
364    172
Name: Subscribers gained, Length: 365, dtype: int64

In [21]:
print(subs.describe())

count    365.000000
mean     135.643836
std       62.675023
min       33.000000
25%       88.000000
50%      123.000000
75%      177.000000
max      396.000000
Name: Subscribers gained, dtype: float64

In [22]:
print(subs.min())

33

In [23]:
print(subs.max())

396

In [25]:
print(subs.median())

123.0

In [29]:
print(subs.sum())

49510

In [36]:
print(subs[subs>200].size) # count() also works

59

In [42]:
print(subs[subs==subs.max()].index)

Int64Index([330], dtype='int64')

<hr>

In [48]:
import pandas as pd

subs=pd.read_csv('bollywood.csv')
print(subs)
print(subs.describe())

                                     movie              lead
0                 Uri: The Surgical Strike     Vicky Kaushal
1                            Battalion 609       Vicky Ahuja
2     The Accidental Prime Minister (film)       Anupam Kher
3                          Why Cheat India     Emraan Hashmi
4                          Evening Shadows  Mona Ambegaonkar
...                                    ...               ...
1495                Hum Tumhare Hain Sanam    Shah Rukh Khan
1496                   Aankhen (2002 film)  Amitabh Bachchan
1497                       Saathiya (film)      Vivek Oberoi
1498                        Company (film)        Ajay Devgn
1499                  Awara Paagal Deewana      Akshay Kumar

[1500 rows x 2 columns]
         movie          lead
count     1500          1500
unique    1497           566
top     Andaaz  Akshay Kumar
freq         2            48

In [50]:
movies=pd.read_csv('bollywood.csv',index_col='movie',squeeze=True)
print(movies)

movie
Uri: The Surgical Strike                   Vicky Kaushal
Battalion 609                                Vicky Ahuja
The Accidental Prime Minister (film)         Anupam Kher
Why Cheat India                            Emraan Hashmi
Evening Shadows                         Mona Ambegaonkar
                                              ...
Hum Tumhare Hain Sanam                    Shah Rukh Khan
Aankhen (2002 film)                     Amitabh Bachchan
Saathiya (film)                             Vivek Oberoi
Company (film)                                Ajay Devgn
Awara Paagal Deewana                        Akshay Kumar
Name: lead, Length: 1500, dtype: object

In [53]:
print(movies.head(10)) # by default 5

movie
Uri: The Surgical Strike                       Vicky Kaushal
Battalion 609                                    Vicky Ahuja
The Accidental Prime Minister (film)             Anupam Kher
Why Cheat India                                Emraan Hashmi
Evening Shadows                             Mona Ambegaonkar
Soni (film)                             Geetika Vidya Ohlyan
Fraud Saiyaan                                   Arshad Warsi
Bombairiya                                      Radhika Apte
Manikarnika: The Queen of Jhansi              Kangana Ranaut
Thackeray (film)                         Nawazuddin Siddiqui
Name: lead, dtype: object

In [55]:
print(movies.tail(3)) # by default 5

movie
Saathiya (film)         Vivek Oberoi
Company (film)            Ajay Devgn
Awara Paagal Deewana    Akshay Kumar
Name: lead, dtype: object

In [56]:
print(movies[0])

Vicky Kaushal

In [57]:
print(movies[-5:])

movie
Hum Tumhare Hain Sanam      Shah Rukh Khan
Aankhen (2002 film)       Amitabh Bachchan
Saathiya (film)               Vivek Oberoi
Company (film)                  Ajay Devgn
Awara Paagal Deewana          Akshay Kumar
Name: lead, dtype: object

In [58]:
print(movies[::2])

movie
Uri: The Surgical Strike                   Vicky Kaushal
The Accidental Prime Minister (film)         Anupam Kher
Evening Shadows                         Mona Ambegaonkar
Fraud Saiyaan                               Arshad Warsi
Manikarnika: The Queen of Jhansi          Kangana Ranaut
                                              ...
Raaz (2002 film)                              Dino Morea
Waisa Bhi Hota Hai Part II                  Arshad Warsi
Kaante                                  Amitabh Bachchan
Aankhen (2002 film)                     Amitabh Bachchan
Company (film)                                Ajay Devgn
Name: lead, Length: 750, dtype: object

In [59]:
print(movies[[0,1,3,7,9,10]])#give indexed movie

movie
Uri: The Surgical Strike          Vicky Kaushal
Battalion 609                       Vicky Ahuja
Why Cheat India                   Emraan Hashmi
Bombairiya                         Radhika Apte
Thackeray (film)            Nawazuddin Siddiqui
Amavas                                Ali Asgar
Name: lead, dtype: object

In [60]:
print('Uri: The Surgical Strike' in movies)

True

In [61]:
print(movies.index)

Index(['Uri: The Surgical Strike', 'Battalion 609',
       'The Accidental Prime Minister (film)', 'Why Cheat India',
       'Evening Shadows', 'Soni (film)', 'Fraud Saiyaan', 'Bombairiya',
       'Manikarnika: The Queen of Jhansi', 'Thackeray (film)',
       ...
       'Raaz (2002 film)', 'Zameen (2003 film)', 'Waisa Bhi Hota Hai Part II',
       'Devdas (2002 Hindi film)', 'Kaante', 'Hum Tumhare Hain Sanam',
       'Aankhen (2002 film)', 'Saathiya (film)', 'Company (film)',
       'Awara Paagal Deewana'],
      dtype='object', name='movie', length=1500)

In [63]:
print(movies.value_counts(ascending=True))

Aarav Khanna         1
Ankit                1
Parzaan Dastur       1
Hema Malini          1
Supriya Pathak       1
                    ..
Sanjay Dutt         26
Salman Khan         31
Ajay Devgn          38
Amitabh Bachchan    45
Akshay Kumar        48
Name: lead, Length: 566, dtype: int64

In [66]:
a=movies.value_counts()
print(a[a>20])# get only 20

Akshay Kumar        48
Amitabh Bachchan    45
Ajay Devgn          38
Salman Khan         31
Sanjay Dutt         26
Shah Rukh Khan      22
Emraan Hashmi       21
Name: lead, dtype: int64

In [67]:
print(a>20)# get all

Akshay Kumar         True
Amitabh Bachchan     True
Ajay Devgn           True
Salman Khan          True
Sanjay Dutt          True
                    ...
Supriya Pathak      False
Hema Malini         False
Parzaan Dastur      False
Ankit               False
Aarav Khanna        False
Name: lead, Length: 566, dtype: bool

In [69]:
import pandas as pd
student_name={'ram':55,'shyam':60,'seeta':65,'geeta':70}
mark_series=pd.Series(student_name)
print(mark_series)

ram      55
shyam    60
seeta    65
geeta    70
dtype: int64

In [70]:
print(list(mark_series))

[55, 60, 65, 70]

In [71]:
print(dict(mark_series))

{'ram': 55, 'shyam': 60, 'seeta': 65, 'geeta': 70}

In [72]:
mark_series[1]=100
print(mark_series)

ram       55
shyam    100
seeta     65
geeta     70
dtype: int64

In [73]:
print(100+mark_series)

ram      155
shyam    200
seeta    165
geeta    170
dtype: int64

In [74]:
print(mark_series)# not changed

ram       55
shyam    100
seeta     65
geeta     70
dtype: int64

In [75]:
print(mark_series>=100)

ram      False
shyam     True
seeta    False
geeta    False
dtype: bool

<hr>

In [78]:
import pandas as pd
a=pd.Series([2,4,6,8,10])
b=pd.Series([1,3,5,7,9])
print(a+b)

0     3
1     7
2    11
3    15
4    19
dtype: int64

In [79]:
print(a-b)

0    1
1    1
2    1
3    1
4    1
dtype: int64

In [80]:
print(a*b)

0     2
1    12
2    30
3    56
4    90
dtype: int64

In [81]:
print(a/b)

0    2.000000
1    1.333333
2    1.200000
3    1.142857
4    1.111111
dtype: float64

In [82]:
print(a==b)

0    False
1    False
2    False
3    False
4    False
dtype: bool

In [83]:
print(a>b)

0    True
1    True
2    True
3    True
4    True
dtype: bool

<hr>

# Data frame

A pandas DataFrame is a two-dimensional, size-mutable, tabular data structure in Python, much like a spreadsheet or SQL table, used for data analysis and manipulation. It is the primary data structure in the pandas library and is built on top of the NumPy package.

In [84]:
import pandas as pd
data={'calories':[420,380,400,370],'duration':[50,40,45,35]}
df=pd.DataFrame(data)
print(df)

   calories  duration
0       420        50
1       380        40
2       400        45
3       370        35

In [85]:
print(df.loc[0])

calories    420
duration     50
Name: 0, dtype: int64

In [86]:
print(df.iloc[0])#  a property in Python's Pandas library used for purely integer-location-based indexing

calories    420
duration     50
Name: 0, dtype: int64

In [87]:
print(df['calories'])

0    420
1    380
2    400
3    370
Name: calories, dtype: int64

In [89]:
print(df.loc[[0,1]])

   calories  duration
0       420        50
1       380        40

In [90]:
df=pd.DataFrame(data,index=['day1','day2','day3','day4'])
print(df)

      calories  duration
day1       420        50
day2       380        40
day3       400        45
day4       370        35

In [93]:
print(df.loc['day1'])

calories    420
duration     50
Name: day1, dtype: int64

In [94]:
print(df.iloc['day1']) # index in form of String so iloc not work

TypeError: Cannot index by location index with a non-integer key

In [95]:
print(df[::2])

      calories  duration
day1       420        50
day3       400        45

In [97]:
import pandas as pd

data={'Name':['Alice','Bod','charlie'],'Age':[25,30,35],'city':['new york','Los Angeles','chicago']}
df=pd.DataFrame(data)
print(df)

      Name  Age         city
0    Alice   25     new york
1      Bod   30  Los Angeles
2  charlie   35      chicago

In [98]:
print(df.loc[0:1]) # 1 is inclusive

    Name  Age         city
0  Alice   25     new york
1    Bod   30  Los Angeles

In [99]:
print(df.iloc[0:1]) # 1 is excusive

    Name  Age      city
0  Alice   25  new york

In [105]:
print(df.loc[(df.Age>26)])

      Name  Age         city
1      Bod   30  Los Angeles
2  charlie   35      chicago

In [123]:
import pandas as pd
data={'A':[1,2,3,4],'B':[5,6,7,8]}
df=pd.DataFrame(data,index=['r1','r2','r3','r4'])
print(df)

    A  B
r1  1  5
r2  2  6
r3  3  7
r4  4  8

In [124]:
df.loc['r2':'r4','B']=99
print(df)

    A   B
r1  1   5
r2  2  99
r3  3  99
r4  4  99

In [125]:
df.iloc[1:3,0]=0
print(df)

    A   B
r1  1   5
r2  0  99
r3  0  99
r4  4  99

In [126]:
df['c']=[10,20,30,40]
print(df)

    A   B   c
r1  1   5  10
r2  0  99  20
r3  0  99  30
r4  4  99  40

In [127]:
df.loc[df['A']==0,'new_col']='Zero'
print(df)

    A   B   c new_col
r1  1   5  10     NaN
r2  0  99  20    Zero
r3  0  99  30    Zero
r4  4  99  40     NaN

In [130]:
df.loc[len(df)]=['John',35,50,'zero']
print(df)

       A   B   c new_col
r1     1   5  10     NaN
r2     0  99  20    Zero
r3     0  99  30    Zero
r4     4  99  40     NaN
4   John  35  50    zero
5   John  35  50    zero

<hr>

In [131]:
import pandas as pd

data={'Name':['Alice','Bod','charlie'],'Age':[25,30,35],'city':['new york','Los Angeles','chicago']}
df=pd.DataFrame(data)
print(df)

      Name  Age         city
0    Alice   25     new york
1      Bod   30  Los Angeles
2  charlie   35      chicago

In [132]:
print(df.index)

RangeIndex(start=0, stop=3, step=1)

In [133]:
print(df.columns)

Index(['Name', 'Age', 'city'], dtype='object')

In [134]:
print(df.size)

9

In [135]:
print(df.values)

[['Alice' 25 'new york']
 ['Bod' 30 'Los Angeles']
 ['charlie' 35 'chicago']]

In [136]:
print(df.dtypes)

Name    object
Age      int64
city    object
dtype: object

In [137]:
print(df.ndim)

2

In [138]:
print(df.shape)

(3, 3)

## set_index()

The set_index() method in the pandas library is used to set one or more existing columns or arrays as the index (row labels) of a DataFrame. This is useful for efficient data retrieval, alignment, and reorganization, especially when working with meaningful identifiers like IDs or dates.

In [32]:
import pandas as pd
data={'Name':['Alice','Bob','charlie'],
     'Age':[25,30,35],
     'city':['New York','Los Angeles','chicago']}
df=pd.DataFrame(data)
print(df)

      Name  Age         city
0    Alice   25     New York
1      Bob   30  Los Angeles
2  charlie   35      chicago

In [24]:
df=df.set_index('Name')
print(df)

         Age         city
Name
Alice     25     New York
Bob       30  Los Angeles
charlie   35      chicago

In [27]:
df.set_index('Name',drop=False)

            Name  Age         city
Name
Alice      Alice   25     New York
Bob          Bob   30  Los Angeles
charlie  charlie   35      chicago

In [31]:
df.set_index('Name',drop=False,inplace=True)# inplace update main df
df

            Name  Age         city
Name
Alice      Alice   25     New York
Bob          Bob   30  Los Angeles
charlie  charlie   35      chicago

In [33]:
a=df.set_index(['Name','Age'],drop=False)
a

                Name  Age         city
Name    Age
Alice   25     Alice   25     New York
Bob     30       Bob   30  Los Angeles
charlie 35   charlie   35      chicago

## reset_index()

The reset_index() method in the pandas library for Python is used to reset the DataFrame's index to the default integer index (0, 1, 2, ...).

In [34]:
df=pd.DataFrame(data,index=['a','b','c'])
df

      Name  Age         city
a    Alice   25     New York
b      Bob   30  Los Angeles
c  charlie   35      chicago

In [38]:
df_reset=df.reset_index()
df_reset

  index     Name  Age         city
0     a    Alice   25     New York
1     b      Bob   30  Los Angeles
2     c  charlie   35      chicago

In [37]:
df_reset=df.reset_index(drop=True)
df_reset

      Name  Age         city
0    Alice   25     New York
1      Bob   30  Los Angeles
2  charlie   35      chicago

In [50]:
df.sample()

  Name  Age         city
b  Bob   30  Los Angeles

## unique() / nunique()

In [51]:
import pandas as pd
data=[[10,20,0],[10,10,10],[10,20,30]]
df=pd.DataFrame(data)
df

    0   1   2
0  10  20   0
1  10  10  10
2  10  20  30

In [53]:
print(df.nunique())# how many data is unique in column

0    1
1    2
2    3
dtype: int64

In [57]:
# unique()  we need to col wise
print(df[1].unique())

[20 10]

In [58]:
import pandas as pd
data={'Region':['North','North','South','South'],
     'city':['New York','LA','Miami','houstan'],
     'population':[8.4,3.9,0.4,2.3]}
df=pd.DataFrame(data)
df

  Region      city  population
0  North  New York         8.4
1  North        LA         3.9
2  South     Miami         0.4
3  South   houstan         2.3

In [59]:
print(df['Region'].unique())
print(df['city'].unique())

['North' 'South']
['New York' 'LA' 'Miami' 'houstan']

In [60]:
print(df.nunique())

Region        2
city          4
population    4
dtype: int64

In [63]:
data= pd.read_csv('auto-mpg.csv')
# print(data)
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 398 entries, 0 to 397
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   mpg           398 non-null    float64
 1   cylinders     398 non-null    int64
 2   displacement  398 non-null    float64
 3   horsepower    398 non-null    object
 4   weight        398 non-null    int64
 5   acceleration  398 non-null    float64
 6   model year    398 non-null    int64
 7   origin        398 non-null    int64
 8   car name      398 non-null    object
dtypes: float64(3), int64(4), object(2)
memory usage: 28.1+ KB

In [64]:
data.head()

    mpg  cylinders  displacement horsepower  weight  acceleration  model year  origin                   car name
0  18.0          8         307.0        130    3504          12.0          70       1  chevrolet chevelle malibu
1  15.0          8         350.0        165    3693          11.5          70       1          buick skylark 320
2  18.0          8         318.0        150    3436          11.0          70       1         plymouth satellite
3  16.0          8         304.0        150    3433          12.0          70       1              amc rebel sst
4  17.0          8         302.0        140    3449          10.5          70       1                ford torino

In [69]:
a=data[data['horsepower']=='?']
a

      mpg  cylinders  displacement horsepower  weight  acceleration  model year  origin              car name
32   25.0          4          98.0          ?    2046          19.0          71       1            ford pinto
126  21.0          6         200.0          ?    2875          17.0          74       1         ford maverick
330  40.9          4          85.0          ?    1835          17.3          80       2  renault lecar deluxe
336  23.6          4         140.0          ?    2905          14.3          80       1    ford mustang cobra
354  34.5          4         100.0          ?    2320          15.8          81       2           renault 18i
374  23.0          4         151.0          ?    3035          20.5          82       1        amc concord dl

In [71]:
data.isna()#True whe null value found

       mpg  cylinders  displacement  horsepower  weight  acceleration  model year  origin  car name
0    False      False         False       False   False         False       False   False     False
1    False      False         False       False   False         False       False   False     False
2    False      False         False       False   False         False       False   False     False
3    False      False         False       False   False         False       False   False     False
4    False      False         False       False   False         False       False   False     False
..     ...        ...           ...         ...     ...           ...         ...     ...       ...
393  False      False         False       False   False         False       False   False     False
394  False      False         False       False   False         False       False   False     False
395  False      False         False       False   False         False       False   False     False
396  False      False         False       False   False         False       False   False     False
397  False      False         False       False   False         False       False   False     False

[398 rows x 9 columns]

In [72]:
data.isna().sum() # where we have null(NaN) in data

mpg             0
cylinders       0
displacement    0
horsepower      0
weight          0
acceleration    0
model year      0
origin          0
car name        0
dtype: int64

In [74]:
data[data['horsepower'].isnull()]

Empty DataFrame
Columns: [mpg, cylinders, displacement, horsepower, weight, acceleration, model year, origin, car name]
Index: []

In [76]:
data.loc[5]

mpg                         15.0
cylinders                      8
displacement               429.0
horsepower                   198
weight                      4341
acceleration                10.0
model year                    70
origin                         1
car name        ford galaxie 500
Name: 5, dtype: object

In [77]:
data.loc[5:10]

     mpg  cylinders  displacement horsepower  weight  acceleration  model year  origin             car name
5   15.0          8         429.0        198    4341          10.0          70       1     ford galaxie 500
6   14.0          8         454.0        220    4354           9.0          70       1     chevrolet impala
7   14.0          8         440.0        215    4312           8.5          70       1    plymouth fury iii
8   14.0          8         455.0        225    4425          10.0          70       1     pontiac catalina
9   15.0          8         390.0        190    3850           8.5          70       1   amc ambassador dpl
10  15.0          8         383.0        170    3563          10.0          70       1  dodge challenger se

In [78]:
data.iloc[5:10]

    mpg  cylinders  displacement horsepower  weight  acceleration  model year  origin            car name
5  15.0          8         429.0        198    4341          10.0          70       1    ford galaxie 500
6  14.0          8         454.0        220    4354           9.0          70       1    chevrolet impala
7  14.0          8         440.0        215    4312           8.5          70       1   plymouth fury iii
8  14.0          8         455.0        225    4425          10.0          70       1    pontiac catalina
9  15.0          8         390.0        190    3850           8.5          70       1  amc ambassador dpl

In [80]:
data['mpg']

0      18.0
1      15.0
2      18.0
3      16.0
4      17.0
       ...
393    27.0
394    44.0
395    32.0
396    28.0
397    31.0
Name: mpg, Length: 398, dtype: float64

In [82]:
data['mpg'].loc[4:6]

4    17.0
5    15.0
6    14.0
Name: mpg, dtype: float64

In [85]:
data.shape

(398, 9)

In [88]:
print(data.shape[1],
data.shape[0])

9 398

In [91]:
data[data['horsepower']=='?'].shape[0] # how many ? in data

6

In [93]:
data.describe() # object column is not available in bellow data

              mpg   cylinders  displacement       weight  acceleration  model year      origin
count  398.000000  398.000000    398.000000   398.000000    398.000000  398.000000  398.000000
mean    23.514573    5.454774    193.425879  2970.424623     15.568090   76.010050    1.572864
std      7.815984    1.701004    104.269838   846.841774      2.757689    3.697627    0.802055
min      9.000000    3.000000     68.000000  1613.000000      8.000000   70.000000    1.000000
25%     17.500000    4.000000    104.250000  2223.750000     13.825000   73.000000    1.000000
50%     23.000000    4.000000    148.500000  2803.500000     15.500000   76.000000    1.000000
75%     29.000000    8.000000    262.000000  3608.000000     17.175000   79.000000    2.000000
max     46.600000    8.000000    455.000000  5140.000000     24.800000   82.000000    3.000000

In [95]:
# percentiles=None, include=None, exclude=None
data.describe(include='all')

               mpg   cylinders  displacement horsepower       weight  acceleration  model year      origin    car name
count   398.000000  398.000000    398.000000        398   398.000000    398.000000  398.000000  398.000000         398
unique         NaN         NaN           NaN         94          NaN           NaN         NaN         NaN         305
top            NaN         NaN           NaN        150          NaN           NaN         NaN         NaN  ford pinto
freq           NaN         NaN           NaN         22          NaN           NaN         NaN         NaN           6
mean     23.514573    5.454774    193.425879        NaN  2970.424623     15.568090   76.010050    1.572864         NaN
std       7.815984    1.701004    104.269838        NaN   846.841774      2.757689    3.697627    0.802055         NaN
min       9.000000    3.000000     68.000000        NaN  1613.000000      8.000000   70.000000    1.000000         NaN
25%      17.500000    4.000000    104.250000        NaN  2223.750000     13.825000   73.000000    1.000000         NaN
50%      23.000000    4.000000    148.500000        NaN  2803.500000     15.500000   76.000000    1.000000         NaN
75%      29.000000    8.000000    262.000000        NaN  3608.000000     17.175000   79.000000    2.000000         NaN
max      46.600000    8.000000    455.000000        NaN  5140.000000     24.800000   82.000000    3.000000         NaN

In [97]:
import numpy as np
data.describe(include=[np.number])

              mpg   cylinders  displacement       weight  acceleration  model year      origin
count  398.000000  398.000000    398.000000   398.000000    398.000000  398.000000  398.000000
mean    23.514573    5.454774    193.425879  2970.424623     15.568090   76.010050    1.572864
std      7.815984    1.701004    104.269838   846.841774      2.757689    3.697627    0.802055
min      9.000000    3.000000     68.000000  1613.000000      8.000000   70.000000    1.000000
25%     17.500000    4.000000    104.250000  2223.750000     13.825000   73.000000    1.000000
50%     23.000000    4.000000    148.500000  2803.500000     15.500000   76.000000    1.000000
75%     29.000000    8.000000    262.000000  3608.000000     17.175000   79.000000    2.000000
max     46.600000    8.000000    455.000000  5140.000000     24.800000   82.000000    3.000000

In [98]:
import numpy as np
data.describe(exclude=[np.number])

       horsepower    car name
count         398         398
unique         94         305
top           150  ford pinto
freq           22           6

In [108]:
data.describe(percentiles=[.40,.60,.98,.80,.20])

              mpg   cylinders  displacement       weight  acceleration  model year      origin
count  398.000000  398.000000    398.000000   398.000000    398.000000  398.000000  398.000000
mean    23.514573    5.454774    193.425879  2970.424623     15.568090   76.010050    1.572864
std      7.815984    1.701004    104.269838   846.841774      2.757689    3.697627    0.802055
min      9.000000    3.000000     68.000000  1613.000000      8.000000   70.000000    1.000000
20%     16.000000    4.000000     98.000000  2155.000000     13.500000   72.000000    1.000000
40%     20.000000    4.000000    122.000000  2580.600000     14.800000   75.000000    1.000000
50%     23.000000    4.000000    148.500000  2803.500000     15.500000   76.000000    1.000000
60%     25.000000    6.000000    200.000000  3085.200000     16.000000   77.000000    1.000000
80%     31.000000    8.000000    304.600000  3806.000000     17.760000   80.000000    2.000000
98%     40.806000    8.000000    429.000000  4732.180000     21.806000   82.000000    3.000000
max     46.600000    8.000000    455.000000  5140.000000     24.800000   82.000000    3.000000

In [109]:
data[['mpg','cylinders']].describe()

              mpg   cylinders
count  398.000000  398.000000
mean    23.514573    5.454774
std      7.815984    1.701004
min      9.000000    3.000000
25%     17.500000    4.000000
50%     23.000000    4.000000
75%     29.000000    8.000000
max     46.600000    8.000000

In [110]:
# for 1 50 data
data[0:50].describe()

             mpg  cylinders  displacement       weight  acceleration  model year    origin
count  50.000000  50.000000      50.00000    50.000000       50.0000   50.000000  50.00000
mean   18.020000   6.480000     268.40000  3364.920000       13.5000   70.420000   1.26000
std     5.108976   1.693204     116.26553   901.242676        2.9277    0.498569   0.59966
min     9.000000   4.000000      97.00000  1835.000000        8.0000   70.000000   1.00000
25%    14.000000   4.500000     154.50000  2598.750000       11.5000   70.000000   1.00000
50%    17.500000   7.000000     280.00000  3381.000000       13.7500   70.000000   1.00000
75%    22.000000   8.000000     357.75000  4195.250000       15.5000   71.000000   1.00000
max    28.000000   8.000000     455.00000  5140.000000       20.5000   71.000000   3.00000

In [113]:
data.corr(numeric_only=True)

                   mpg  cylinders  displacement    weight  acceleration  model year    origin
mpg           1.000000  -0.775396     -0.804203 -0.831741      0.420289    0.579267  0.563450
cylinders    -0.775396   1.000000      0.950721  0.896017     -0.505419   -0.348746 -0.562543
displacement -0.804203   0.950721      1.000000  0.932824     -0.543684   -0.370164 -0.609409
weight       -0.831741   0.896017      0.932824  1.000000     -0.417457   -0.306564 -0.581024
acceleration  0.420289  -0.505419     -0.543684 -0.417457      1.000000    0.288137  0.205873
model year    0.579267  -0.348746     -0.370164 -0.306564      0.288137    1.000000  0.180662
origin        0.563450  -0.562543     -0.609409 -0.581024      0.205873    0.180662  1.000000